# Clean-LocalComet.ps1
# Safe cleanup of rebuildable artifacts for LocalComet development.
# Deletes ONLY regenerable output: Rust target dir, SvelteKit caches,
# localcomet_* test leftovers in %TEMP%. Never touches node_modules,
# sources, artifacts/gate-reports, or the global cargo registry cache.
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\Clean-LocalComet.ps1          # report + clean
#   powershell -ExecutionPolicy Bypass -File .\Clean-LocalComet.ps1 -DryRun  # report only

param(
    [switch]$DryRun
)

$ErrorActionPreference = 'Continue'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$desktop = Join-Path $root 'desktop\localcomet-desktop'
$tempRoot = [System.IO.Path]::GetTempPath().TrimEnd('\')

function Measure-DirSize([string]$path) {
    if (-not (Test-Path -LiteralPath $path)) { return 0.0 }
    $sum = (Get-ChildItem -LiteralPath $path -Recurse -Force -File -ErrorAction SilentlyContinue |
        Measure-Object -Property Length -Sum).Sum
    if ($null -eq $sum) { return 0.0 }
    return [double]$sum
}

function Format-GB([double]$bytes) {
    return ('{0:N2} GB' -f ($bytes / 1GB))
}

function Test-InsideRepo([string]$path) {
    $full = [System.IO.Path]::GetFullPath($path)
    return $full.StartsWith($root, [System.StringComparison]::OrdinalIgnoreCase)
}

# Deletable targets: everything here is regenerated by the toolchain.
$targets = @(
    @{ Path = (Join-Path $desktop 'src-tauri\target'); Label = 'Rust build cache'; Rebuild = 'cargo test/build recompiles (slow first run after clean)' },
    @{ Path = (Join-Path $desktop '.svelte-kit');      Label = 'SvelteKit dev cache'; Rebuild = 'npm run dev regenerates' },
    @{ Path = (Join-Path $desktop 'build');            Label = 'SvelteKit production build'; Rebuild = 'npm run build regenerates' }
)

# Report-only targets: measured so the picture is complete, never deleted.
$reportOnly = @(
    @{ Path = (Join-Path $desktop 'node_modules');        Label = 'npm dependencies (kept: npm ci needs network + time)' },
    @{ Path = (Join-Path $root 'artifacts\gate-reports'); Label = 'gate reports (kept: evidence history)' }
)

# Abort if a dev/build process could hold locks on the target dir.
$busy = Get-Process -ErrorAction SilentlyContinue | Where-Object { $_.Name -match '^(cargo|rustc|localcomet|LocalComet)' }
if ($busy -and -not $DryRun) {
    Write-Host 'ABORTED: cargo/rustc/LocalComet process is running. Close the app and builds first, then re-run.' -ForegroundColor Red
    exit 1
}

Write-Host '=== Size report ==='
$totalFreed = 0.0
foreach ($t in $targets) {
    $size = Measure-DirSize $t.Path
    $mark = if ($DryRun) { 'would delete' } else { 'will delete' }
    Write-Host (('{0,10}  {1}  [{2}]' -f (Format-GB $size), $t.Path, $mark))
    Write-Host ('            {0}: {1}' -f $t.Label, $t.Rebuild)
}
foreach ($t in $reportOnly) {
    $size = Measure-DirSize $t.Path
    Write-Host (('{0,10}  {1}  [kept]' -f (Format-GB $size), $t.Path))
    Write-Host ('            {0}' -f $t.Label)
}

$tempItems = @(Get-ChildItem -LiteralPath $tempRoot -Directory -Filter 'localcomet_*' -Force -ErrorAction SilentlyContinue)
$tempSize = 0.0
foreach ($item in $tempItems) { $tempSize += Measure-DirSize $item.FullName }
Write-Host (('{0,10}  {1}\localcomet_*  ({2} dirs, test leftovers)' -f (Format-GB $tempSize), $tempRoot, $tempItems.Count))

if ($DryRun) {
    Write-Host ''
    Write-Host 'DRY RUN: nothing deleted. Re-run without -DryRun to clean.' -ForegroundColor Cyan
    exit 0
}

Write-Host ''
Write-Host '=== Cleaning ==='
foreach ($t in $targets) {
    if (-not (Test-Path -LiteralPath $t.Path)) { continue }
    if (-not (Test-InsideRepo $t.Path)) {
        Write-Host ('SKIP outside repo: {0}' -f $t.Path) -ForegroundColor Yellow
        continue
    }
    $size = Measure-DirSize $t.Path
    try {
        Remove-Item -LiteralPath $t.Path -Recurse -Force -ErrorAction Stop
        $totalFreed += $size
        Write-Host ('DELETED {0}  ({1})' -f $t.Path, (Format-GB $size))
    } catch {
        Write-Host ('FAILED  {0}  ({1})' -f $t.Path, $_.Exception.Message) -ForegroundColor Red
    }
}
foreach ($item in $tempItems) {
    $size = Measure-DirSize $item.FullName
    try {
        Remove-Item -LiteralPath $item.FullName -Recurse -Force -ErrorAction Stop
        $totalFreed += $size
    } catch {
        Write-Host ('FAILED  {0}  ({1})' -f $item.FullName, $_.Exception.Message) -ForegroundColor Red
    }
}

$driveLetter = $root.Substring(0, 1)
$drive = Get-PSDrive -Name $driveLetter -ErrorAction SilentlyContinue
Write-Host ''
Write-Host ('Freed total: {0}' -f (Format-GB $totalFreed))
if ($drive) {
    Write-Host ('Drive {0}: free space now {1}' -f $drive.Name, (Format-GB ([double]$drive.Free)))
}
Write-Host 'Done. Next cargo/npm run will rebuild the deleted caches (slower once, then normal).'
