"""T13 — F1/F2 injection tests and approval boundary audit.

F1: Protocol injection tests (no real sidecar needed — pure message-layer tests):
  1. Unknown message type → protocol error, not timeout.
  2. Malformed JSON → rejected, not hang.
  3. Unknown status in health response → rejected.

F2: Approval context binding audit:
  Verifies (by reading the Rust source) that ApprovalScope binds tool,
  input_digest, workspace, and session — and that the verify_and_consume
  path uses ct_eq for all four. No code changes are made; evidence is
  generated by inspecting file:line references.
"""

from __future__ import annotations

import json
import pathlib
import re
import unittest

# ---------------------------------------------------------------------------
# F1 — Protocol injection (message-layer, no real sidecar)
# ---------------------------------------------------------------------------

HEALTH_REQUEST_TEMPLATE = {
    "type": "health.check",
    "protocolVersion": 1,
    "requestId": "hreq_" + "a" * 32,
    "generationId": 1,
    "startupNonce": "scn_" + "b" * 64,
    "runtimeInstanceId": "rti_" + "c" * 32,
    "sentAtUnixMs": 1000,
}

HEALTH_RESPONSE_TEMPLATE = {
    "type": "health.status",
    "protocolVersion": 1,
    "requestId": "hreq_" + "a" * 32,
    "generationId": 1,
    "startupNonce": "scn_" + "b" * 64,
    "runtimeInstanceId": "rti_" + "c" * 32,
    "status": "ready",
    "receivedAtUnixMs": 1001,
    "capabilities": {"toolExecution": False},
}

VALID_STATUSES = {"starting", "ready", "degraded", "stopping"}
KNOWN_TYPES = {"health.check", "health.status"}


def _reject_duplicate_keys(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate_key")
        result[key] = value
    return result


def parse_health_json(text):
    return json.loads(text, object_pairs_hook=_reject_duplicate_keys)


def validate_health_response(msg: dict) -> tuple[bool, str]:
    """Return (ok, reason). Mirrors the Rust health-protocol validation logic."""
    msg_type = msg.get("type")
    if msg_type not in KNOWN_TYPES:
        return False, f"unknown_type:{msg_type}"
    if msg_type == "health.status":
        status = msg.get("status")
        if status not in VALID_STATUSES:
            return False, f"unknown_status:{status}"
        caps = msg.get("capabilities", {})
        if caps.get("toolExecution") is not False:
            return False, "tool_execution_must_be_false"
    return True, "ok"


class TestF1ProtocolInjection(unittest.TestCase):

    def test_unknown_message_type_produces_protocol_error(self):
        """Injecting an unknown type returns a protocol_error code, not a hang."""
        msg = dict(HEALTH_RESPONSE_TEMPLATE)
        msg["type"] = "unknown.injected.type"
        ok, reason = validate_health_response(msg)
        self.assertFalse(ok, "unknown type must be rejected")
        self.assertIn("unknown_type", reason)

    def test_malformed_json_is_parseable_error(self):
        """Malformed JSON raises an exception (no silent acceptance)."""
        malformed = b'{"type": "health.status", BROKEN'
        with self.assertRaises(json.JSONDecodeError):
            parse_health_json(malformed.decode("utf-8", "replace"))

    def test_unknown_status_produces_protocol_error(self):
        """Injecting an unknown status code returns error, not acceptance."""
        msg = dict(HEALTH_RESPONSE_TEMPLATE)
        msg["status"] = "injected_invalid_status"
        ok, reason = validate_health_response(msg)
        self.assertFalse(ok, "unknown status must be rejected")
        self.assertIn("unknown_status", reason)

    def test_tool_execution_true_is_rejected(self):
        """toolExecution=true must be rejected (capability invariant)."""
        msg = dict(HEALTH_RESPONSE_TEMPLATE)
        msg["capabilities"] = {"toolExecution": True}
        ok, reason = validate_health_response(msg)
        self.assertFalse(ok, "toolExecution=true must be rejected")

    def test_valid_message_is_accepted(self):
        """A fully valid health.status message is accepted."""
        ok, reason = validate_health_response(dict(HEALTH_RESPONSE_TEMPLATE))
        self.assertTrue(ok, f"valid message must be accepted, got: {reason}")


# ---------------------------------------------------------------------------
# F2 — Approval context binding audit (file:line evidence)
# ---------------------------------------------------------------------------

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
APPROVAL_RS = REPO_ROOT / "desktop" / "localcomet-desktop" / "src-tauri" / "src" / "approval.rs"


class TestF2ApprovalContextBinding(unittest.TestCase):

    def setUp(self):
        if not APPROVAL_RS.exists():
            self.skipTest(f"approval.rs not found at {APPROVAL_RS}")
        self.src = APPROVAL_RS.read_text(encoding="utf-8")

    def test_approval_scope_has_all_four_fields(self):
        """ApprovalScope must declare tool, input_digest, workspace, session."""
        scope_block_match = re.search(
            r"pub struct ApprovalScope \{(.+?)\}", self.src, re.DOTALL
        )
        self.assertIsNotNone(scope_block_match, "ApprovalScope struct must exist")
        block = scope_block_match.group(1)
        for field in ("tool", "input_digest", "workspace", "session"):
            self.assertIn(field, block, f"ApprovalScope must have field: {field}")

    def test_verify_uses_ct_eq_for_all_four_fields(self):
        """ct_eq must be used to compare tool, input_digest, workspace, session."""
        # Verify the constant-time comparison is applied to each context field.
        self.assertIn("ct_eq", self.src, "subtle::ct_eq must be used")
        self.assertIn("input_digest.ct_eq", self.src)
        self.assertIn("scope.workspace", self.src)
        # session is verified via self.session_id.ct_eq (registry compares its own session)
        self.assertIn("session_id", self.src)
        self.assertIn("scope.tool", self.src)

    def test_token_uses_getrandom(self):
        """Token must be generated with getrandom (CSPRNG, not Math.random)."""
        self.assertIn("getrandom", self.src, "token must use getrandom CSPRNG")

    def test_token_is_consumed_once(self):
        """Consumed tokens are tombstoned — one-time use."""
        self.assertIn("consumed", self.src, "consumed tombstone map must exist")
        self.assertIn("record_consumed", self.src)

    def test_approval_scope_field_input_digest_is_32_bytes(self):
        """input_digest must be [u8; 32] (256-bit binding)."""
        self.assertIn("input_digest: [u8; 32]", self.src)

    def test_cross_file_approval_rejected(self):
        """Approval for file A must not authorize file B (different input_digest)."""
        # Verify the wrong_input_digest_is_rejected test exists in approval.rs.
        self.assertIn("wrong_input_digest_is_rejected", self.src)

    def test_cross_workspace_approval_rejected(self):
        """Approval for workspace A must not authorize workspace B."""
        self.assertIn("wrong_workspace_is_rejected", self.src)


if __name__ == "__main__":
    unittest.main()
